parentConfigurationFile: configs/base.yaml

server:
    applicationConnectors:
        - type: "http"
          port: 7000
    adminConnectors:
        - type: "http"
          port: 7001

environmentName: dev

consulEndpoint: http://dev-wiz-01:8500

configChangePublish:
  # Controls which destinations we publish config changes to.
  # Subscribers: We publish to all subscribers who registered with us (ConfigChangeResource)
  # PublishUrl: We publish to the configured publishUrl
  # Both: Both the above
  # None: Config changes will not be published
  strategy: Both
  publishUrl: http://localhost:9000/configChange

namespaceLevels:
  - label: "Service"
    description: "The micro-service whose config is represented"
  - label: "Region"
    defaultValue: "dev"
    description: "The Cvent region name"
  - label: "Branch"
    defaultValue: "master"
    description: "The git branch where this config is maintained"